### PR TITLE
Organize CI configuration and gem dependencies

### PR DESCRIPTION
**Pull request by okkez**

### CODE REVIEW

**Comment by okkez** [comment]
CI will pass after merge https://github.com/fluent/fluentd/pull/1295 and release new version of Fluentd v0.10.x.

**Comment by okkez** [comment]
I've checked using https://github.com/fluent/fluentd/pull/1295 for Fluentd v0.10.x
Result: https://travis-ci.org/okkez/fluent-plugin-notifier/builds/171272160

**Comment by tagomoris** [comment]
In my opinion, it's not good idea to take huge effort to support older versions of Fluentd with this plugin... So I'll decline this change.
Thank you to propose this!

**Comment by okkez** [comment]
OK, thank you for response!

**Pull request closed without merging**
